@baseUrl = http://127.0.0.1:8000/api/v1
@token = 3|RDZJawJpe6f9wLlwicmjzH1aeNO7RifIpJeGzLx47264577b

### 1. POST AUTH LOGIN
# Endpoint untuk login pegawai
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
    "phone": "123456789012",
    "password": "admin123"
}

### 2. POST CREATE EMPLOYEE (Lengkap)
# Endpoint untuk menambahkan data pegawai baru (memerlukan Bearer Token & permission: employee.create)
POST {{baseUrl}}/employees
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "store_code": "STR-B-KXQUN2IL",
    "name": "Budi Santoso",
    "email": "budi.santoso@example.com",
    "phone": "081298765432",
    "password": "password123",
    "address": "Jl. Gatot Subroto No. 45, Jakarta",
    "position": "Kasir"
}

### 3. POST CREATE EMPLOYEE (Field Wajib Saja)
# Email dan address bersifat nullable
POST {{baseUrl}}/employees
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
    "store_code": "STR-B-KXQUN2IL",
    "name": "Siti Aminah",
    "phone": "081311223344",
    "password": "password123",
    "position": "Staff Gudang"
}
