@baseUrl = http://127.0.0.1:8000/api/v1

### 1. POST CREATE MEMBER
POST {{baseUrl}}/members
Content-Type: application/json
Accept: application/json

{
    "name": "Wilimaxs",
    "email": "wildan@example.com",
    "phone": "081322325444",
    "address": "Garut, Indonesia",
    "is_active": true
}

### 2. GET ALL MEMBERS (Pagination default 20)
GET {{baseUrl}}/members
Accept: application/json

### 3. GET MEMBERS WITH SEARCH (Filter berdasarkan kode member / nama)
GET {{baseUrl}}/members?search=Wilimaxs
Accept: application/json

### 4. GET MEMBERS WITH FILTER STATUS AKTIF
GET {{baseUrl}}/members?is_active=1
Accept: application/json

### 5. GET MEMBERS WITH SEARCH AND FILTER STATUS
GET {{baseUrl}}/members?search=Wilimaxs&is_active=1
Accept: application/json

### 6. GET MEMBERS PAGINATION (Page 2)
GET {{baseUrl}}/members?page=2
Accept: application/json

### 7. PATCH UPDATE MEMBER DATA
PATCH {{baseUrl}}/members/MBR-NE5BXYSM
Content-Type: application/json
Accept: application/json

{
    "name": "Wildan",
    "email": "wawan.updated@example.com",
    "phone": "081399998888",
    "address": "Bandung, Indonesia",
    "is_active": true
}
